### ISSUE TITLE
dpinger fails to start on IPv6 IPs considered "tentative"

### ISSUE THREAD

**Issue by rbgarga** [dennypage/dpinger#16]
For reference: https://redmine.pfsense.org/issues/5696

**Comment by rbgarga** [comment]
We fixed it on pfSense, case you think the patch is interesting for dpinger, please let me know and I can submit a PR - https://github.com/pfsense/dpinger/commit/7afb2e97af4ea8705189cbd66455bd029a9f5c38

**Comment by dennypage** [comment]
The general consensus in the open source community is that this race condition should be addressed with a script controlling interface startup rather than in individual applications.

**Comment by rbgarga** [comment]
OK
