### ISSUE TITLE
Collecting Stats

### ISSUE THREAD

**Issue by jwhostet** [dennypage/dpinger#20]
Good morning,

In your readme you state dpinger can provide information to "Cacti, Nagios, Zabbix, etc." 

How would you go about getting the dpinger stats to a monitoring tool? I would like to run dpinger on a mips linux based router. Compiling dpinger with static binary is no problem and everything seems to work. However I am not sure what the best way to get data to one of the monitoring tools.

Thanks!
Josh

**Comment by dennypage** [comment]
Hey Josh,

To collect info with Cacti on the local host, you set dpinger up to write to a status file (-o option) and use a cacti script to pull the data at each polling interval. See cacti_home/scripts for examples. Or if you prefer SNMP or need remote monitoring, you can use net-snmp's extend functionality. See snmpd.conf.example for examples.

Denny
