### ISSUE TITLE
pidfile not checked

### ISSUE THREAD

**Issue by dhoffend** [dennypage/dpinger#21]
dpinger doesn't check the pidfile when it's specified. This can lead problems that you've multiple dpinger daemons running that all write the same pidfile and likely will even have problems when they all try to use the same socketfilename.

IMO: During starting dpinger should check if a pidfile already exists and check it's content (ping process to detect orphaned pidfiles.

**Comment by dennypage** [comment]
I originally stayed with the traditional create but don't check due to portability issues. When I have time I will look at the pidfile(3) routines under Linux to see if they are suitable now.

**Comment by dennypage** [comment]
Done (finally :)
