### ISSUE TITLE
Remove DISABLE_ACCEPT4

### ISSUE THREAD

**Issue by dennypage** [dennypage/dpinger#30]
Prior accept() behavior use can be restored by defining DISABLE_ACCEPT4. If you have a platform where this is necessary, please add a comment to this issue explaining the circumstance. If no one comments, the conditional will be removed in a future release.

**Comment by luckman212** [comment]
Not sure if there have been any other comments, but at least for me, I needed `DISABLE_ACCEPT4` to get dpinger to compile on macOS. So maybe that is one valid reason to leave this alone?

I found 2 ways to compile it:

using **cmake**:
```
echo -e 'cmake_minimum_required(VERSION 3.6)\nproject(dpinger)\nset(CMAKE_CXX_STANDARD 11)\nset(SOURCE_FILES dpinger.c)\nadd_compile_definitions(DISABLE_ACCEPT4)\nadd_executable(dpinger ${SOURCE_FILES})' >CMakeLists.txt
mkdir build; cd build
cmake ..; make
```
using **clang**:
```
clang -DDISABLE_ACCEPT4 dpinger.c -o dpinger`
```

**Comment by dennypage** [comment]
Okay, thanks for the note.

**Comment by dennypage** [comment]
As MacOS still hasn't implemented accept4() [sigh], I'm going to leave the conditional in place and close this issue.
