### ISSUE TITLE
Very handy app! But missing some features!

### ISSUE THREAD

**Issue by Marctraider** [dennypage/dpinger#33]
Would be nice to also have:

- combine loss/latency so it stays on alert until both latency and loss < threshold.

- Even better, not only execute command if > threshold, but also another command (or script) if back to < threshold. Also with optional function like above.

Thanks anyway, this is great small tool for various things.

**Comment by dennypage** [comment]
Dpinger already does this. The alert_cmd is invoked when either threshold is exceeded, and again when both are below their respective threshold values. There is a flag that indicates the status.

From the notes section of the usage output:

    the alert_cmd is invoked as "alert_cmd dest_addr alarm_flag latency_avg loss_avg"
    alarm_flag is set to 1 if either latency or loss is in alarm state
    alarm_flag will return to 0 when both have have cleared alarm state

**Comment by Marctraider** [comment]
Yes, but it executes the same command. Would be handy if you could define a different command for both ^ and v

Now i refrain to creating a bash script to read values of dpinger latest readings and make my own threshold script which executes command1 on > threshold and command2 on < threshold.

Basically making the tool useless (for me). This small function would suddenly make it work perfect out of the box without any inefficient side scripting.

**Comment by luckman212** [comment]
yes @Marctraider but the alarm_flag parameter is passed along with it so you can wrap whatever command(s) you want to execute in a shell script and do different things for each case.

**Comment by Marctraider** [comment]
> yes @Marctraider but the alarm_flag parameter is passed along with it so you can wrap whatever command(s) you want to execute in a shell script and do different things for each case.

I know, but i just hoped it could be done more clean.

Anyway ill try and tinker with the code, sadly i have zero C skills hah.

**Comment by luckman212** [comment]
Why do you say it's not "clean"? Actually by calling the same command you can avoid hysteresis which is a good thing. You don't need any C code to do this- just shell scripting.

**Comment by dennypage** [comment]
Generally, you want the same command to handle both transitions. However, if you are real excited about using different commands, it's a simple script.

```
#!/bin/sh

dest_addr="$1"
alarm_flag="$2"
latency_avg="$3"
loss_avg="$4"

if [ "$alarm_flag" -eq 1 ]
then
    my_alarm_cmd "$dest_addr" "$latency_avg" "$loss_avg"
else
    my_clear_cmd "$dest_addr" "$latency_avg" "$loss_avg"
fi
```

**Comment by Marctraider** [comment]
@dennypage Thank you, I will try and implement it this way. I wasn't aware you could use the variables like this that get passed on. Makes sense now! 

Another minor question, I need to monitor individual wan interfaces outside of my vpn tunnel (normally whole network routes over this) and usually i use ping -I interface for this, I assume 'bind source address' works similar, but what about changing dhcp on the interfaces? Or do I ping to gateway ip of those? (That dont change i think)

**Comment by dennypage** [comment]
Binding the source IP address is a one time operation. If your source IP address changes, you would need to start a new instance of dpinger. That said, you probably do not need to bind a source address. This is generally used when you have a device, such as a firewall, that has redundant paths to the same destination and you need to monitor individual latency/loss on those paths.

**Comment by Marctraider** [comment]
That is the setup I'm currently running, A redundant path from multiple ISP's to a single VPS ;-)
