### ISSUE TITLE
argument to define interface instead of ip

### ISSUE THREAD

**Issue by cyayon** [dennypage/dpinger#34]
Hello,

I would be great if we could define interface name instead of source ip address.

thanks

**Comment by dennypage** [comment]
While I appreciate the interest, a conscious decision was made not to implement convenience functions like name resolution for targets or interface binding. These types of things very from system to system, return multiple results, and are rather complex to implement portably. They are also easy to handle externally with scripts, and commonly have to be to ensure the correct result. Implementing them inside of dpinger would be a lot of complexity for very little return.

An example looking at interface names in particular... the most common use case for dpinger is on a firewall. In that use case, it is common that an interface has multiple IP addresses assigned to it. Which do you choose? The first address in the array is frequently the wrong choice. And choosing one at random is simply a bad idea. It's much better, and usually much simpler, to externally determine the IP address you wish to bind to and provide that information to dpinger.
