### ISSUE TITLE
Command not running on failure

### ISSUE THREAD

**Issue by micush** [dennypage/dpinger#38]
Hi,

I run the following:

dpinger -r 0 -S -D 100m -L 2 -C /usr/sbin/reboot -f 192.168.1.1

On failure nothing happens. Am I misunderstanding or missing something?

**Comment by dennypage** [comment]
By "failure" do you mean that either the 100ms latency or 2% loss threshold is exceeded?

Assuming so, have you turned reporting on to confirm that either threshold is actually being exceeded?
Also, does the user you are running as have privilege to execute the command you are using (/usr/sbin/reboot)?

As an aside, this seems like a dangerous configuration to me. It could easily end up rebooting the system unexpectedly, particularly if run at startup.

**Comment by micush** [comment]
Hi,

It's just an example. It doesn't matter what I put in there, it doesn't run. I pull the cable out of the back of the machine and wait and nothing ever happens other than syslog entries saying there's a failure and that the message is repeated X amount of times.

-m

**Comment by dennypage** [comment]
FWIW, pulling the cable out of the back of the machine isn't a reasonable way to simulate packet loss.

You're saying "failure," but it would be helpful if you were more specific about what you are referring to. Hopefully you do not mean sendto() failures.

I would recommend that you turn on the report (-r 1) while you are attempting to troubleshoot.
