### ISSUE TITLE
Changing the send_interval causes wildly different latency results

### ISSUE THREAD

**Issue by rlabrecque** [dennypage/dpinger#40]
I've spent much of my day debugging my Unifi Dream Machine Pro's latency metrics which are not in line with reality on my Quantum Fiber 2/1Gbps internet. Ultimately this lead me here.

I'll let these 3 outputs do most of the talking, the dpinger binary I am using for this test is 3.3 compiled locally from https://github.com/dennypage/dpinger/commit/193f83db0abfba98e3b139b4a72968605ffebe6c. But I was first experiencing this on Unifi's unversioned copy of dpinger.

```
ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=56 time=4.65 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=56 time=3.68 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=56 time=4.46 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=56 time=4.18 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=56 time=3.91 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=56 time=3.64 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=56 time=3.72 ms
64 bytes from 1.1.1.1: icmp_seq=8 ttl=56 time=4.02 ms
```

```
sudo ./dpinger -f 1.1.1.1
send_interval 500ms  loss_interval 2000ms  time_period 60000ms  report_interval 1000ms  data_len 0  alert_interval 1000ms  latency_alarm 0ms  loss_alarm 0%  alarm_hold 10000ms  dest_addr 1.1.1.1  bind_addr (none)  identifier ""
135168 36226 0
257879 153114 0
195028 154650 0
169796 146250 0
150217 136557 0
144098 129654 0
125740 128211 0
137954 139087 0
154539 147717 0
```

```
sudo ./dpinger -s 1 -f 1.1.1.1
send_interval 1ms  loss_interval 4ms  time_period 60000ms  report_interval 1000ms  data_len 0  alert_interval 1000ms  latency_alarm 0ms  loss_alarm 0%  alarm_hold 10000ms  dest_addr 1.1.1.1  bind_addr (none)  identifier ""
4152 1076 0
4154 1087 0
4128 1059 0
4104 1039 0
4100 1034 0
4108 1086 0
4109 1079 0
```

Am I wrong in assuming that send_interval should have basically no impact on those numbers aside from the frequency?
Or would this be expected especially with a network misconfiguration either locally or on my ISP's side? Obviously not everyone's hitting this, so I imagine there's /some/ network configuration involvement.

Here's the primary thread on this issue on the Unifi side: https://community.ui.com/questions/High-latency-network-issues-on-new-UDM-Pro/512170f8-cad0-48db-ae43-22e9fb518b90?page=1 but there's a few dozen smaller threads scattered around.
The solution in that thread is basically to end up doing `dpinger localhost` which defeats the purpose entirely.

Thanks,
Riley

---

Edit:

I got to try on my work machine in the office; and there was a tiny difference but not what I was seeing here.

```
$ sudo ./dpinger -s 500 -f 1.1.1.1
send_interval 500ms  loss_interval 2000ms  time_period 60000ms  report_interval 1000ms  data_len 0  alert_interval 1000ms  latency_alarm 0ms  loss_alarm 0%  alarm_hold 10000ms  dest_addr 1.1.1.1  bind_addr (none)  identifier ""
2509 22 0
2485 61 0
2543 151 0
2514 145 0
2540 165 0
2544 142 0
2531 144 0

$ sudo ./dpinger -s 1 -f 1.1.1.1
send_interval 1ms  loss_interval 4ms  time_period 60000ms  report_interval 1000ms  data_len 0  alert_interval 1000ms  latency_alarm 0ms  loss_alarm 0%  alarm_hold 10000ms  dest_addr 1.1.1.1  bind_addr (none)  identifier ""
2264 75 0
2259 129 0
2258 123 0
2258 114 0
2272 294 0
2272 282 0

**Comment by dennypage** [comment]
Several things...

Throughput and latency are not the same thing. A 2Gb/s connection doesn't intrinsically have lower latency than a 100Mb/s connection.

The first and foremost issue would be running dpinger with a 1ms send rate. Sending 100 ICMP packets per second across the internet to Cloudflare is a bad idea. With these kind of rates, either your ISP or Cloudflare is going to start shaping (rate limiting) or dropping your ICMP packets. Also, the loss interval is around your minimum round trip time which is going to mess everything up quite a bit. It needs to be much longer.

I highly recommend that you do not exceed a 250ms send rate. Here's a reasonable command to try: `dpinger -f -s 250m -l 5s 1.1.1.1`.

Another issue when comparing with ping will be the payload size. By default dpinger uses a payload of size 0 (option -d), whereas ping usually defaults to a payload size of 56 bytes (option -s to ping).

If you need to compare ping with dpinger, you want to either increase the size of the dpinger payload or decrease the size of the ping payload. 16 would be a reasonable value. Examples:
`dpinger -f -s 1s -d 16 1.1.1.1`
`ping -s 16 1.1.1.1`

HTH

**Comment by rlabrecque** [comment]
This has been super helpful.

Looks like it is indeed the payload size that makes a big difference.

```
$ ping -s 16 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 16(44) bytes of data.
24 bytes from 1.1.1.1: icmp_seq=1 ttl=56 time=3.91 ms
24 bytes from 1.1.1.1: icmp_seq=2 ttl=56 time=3.67 ms
24 bytes from 1.1.1.1: icmp_seq=3 ttl=56 time=4.62 ms
24 bytes from 1.1.1.1: icmp_seq=4 ttl=56 time=3.53 ms
24 bytes from 1.1.1.1: icmp_seq=5 ttl=56 time=3.68 ms

$ sudo ./dpinger -f -s 1s -d 16 1.1.1.1
send_interval 1000ms  loss_interval 4000ms  time_period 60000ms  report_interval 1000ms  data_len 16  alert_interval 1000ms  latency_alarm 0ms  loss_alarm 0%  alarm_hold 10000ms  dest_addr 1.1.1.1  bind_addr (none)  identifier ""
4369 0 0
4227 155 0
4049 286 0
4144 293 0
4171 271 0
4101 297 0
4015 343 0

$  sudo ./dpinger -f -s 1s 1.1.1.1
send_interval 1000ms  loss_interval 4000ms  time_period 60000ms  report_interval 1000ms  data_len 0  alert_interval 1000ms  latency_alarm 0ms  loss_alarm 0%  alarm_hold 10000ms  dest_addr 1.1.1.1  bind_addr (none)  identifier ""
331027 0 0
192448 138579 0
281640 169451 0

$ sudo ./dpinger -f -s 1s -d 6 1.1.1.1
send_interval 1000ms  loss_interval 4000ms  time_period 60000ms  report_interval 1000ms  data_len 6  alert_interval 1000ms  latency_alarm 0ms  loss_alarm 0%  alarm_hold 10000ms  dest_addr 1.1.1.1  bind_addr (none)  identifier ""
246542 0 0
318470 71930 0

$ sudo ./dpinger -f -s 1s -d 7 1.1.1.1
send_interval 1000ms  loss_interval 4000ms  time_period 60000ms  report_interval 1000ms  data_len 7  alert_interval 1000ms  latency_alarm 0ms  loss_alarm 0%  alarm_hold 10000ms  dest_addr 1.1.1.1  bind_addr (none)  identifier ""
4371 0 0
4225 159 0
4392 275 0
```

Seems like the data length needs to be at least 7 bytes for me to be seeing reasonable/expected numbers. Now to start investigating whether this is my home network causing this or my ISP doing packet shaping or batching of packets smaller than the ICMP header + a 7 byte payload. One oddity is that below 16 bytes iputils ping stops returning the time for some reason.

By going down to a send rate of 1ms I was probably hitting that batch rate immediately or overflowing something.

Feel free to close this, I might keep posting in here and keeping this updated with my findings though.

It would be nice if Ubuiqiti would just let us set some dpinger parameters other than the dest_addr; though I guess ideally this sounds like it really shouldn't be necessary and the defaults really should just be working fine.

Edit: Reduced my home network down to just my PC connected right into my Q1000K ONT which is in bridge mode; still observing this, so it really must be solely on Quantums side in my case. (Xfinity seems to be the largest problem ISP for this exact situation though.)

Edit2: Reproduced this with ping on Windows. (I couldn't with iputils ping because it wouldn't give me the latency when `ping -s` was below 16)

```
> ping -l 0 1.1.1.1

Pinging 1.1.1.1 with 0 bytes of data:
Reply from 1.1.1.1: bytes=0 time=269ms TTL=57
Reply from 1.1.1.1: bytes=0 time=145ms TTL=57
Reply from 1.1.1.1: bytes=0 time=228ms TTL=57
Reply from 1.1.1.1: bytes=0 time=4ms TTL=57

Ping statistics for 1.1.1.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 4ms, Maximum = 269ms, Average = 161ms

> ping 1.1.1.1

Pinging 1.1.1.1 with 32 bytes of data:
Reply from 1.1.1.1: bytes=32 time=3ms TTL=57
Reply from 1.1.1.1: bytes=32 time=3ms TTL=57
Reply from 1.1.1.1: bytes=32 time=3ms TTL=57
Reply from 1.1.1.1: bytes=32 time=4ms TTL=57

Ping statistics for 1.1.1.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 3ms, Maximum = 4ms, Average = 3ms
```

**Comment by dennypage** [comment]
> One oddity is that below 16 bytes iputils ping stops returning the time for some reason.

ICMP Echo Reply reflects the same data payload that was in the ICMP Echo Request. Ping puts the original timestamp in the data payload, and depends upon the timestamp being returned by the target. If there is no room for a timestamp in the packet, ping cannot calculate the elapsed time.

Dpinger keeps track of time without using the data payload.

**Comment by rlabrecque** [comment]
Hokay I figured this out!

My Q1000K ONT which was in transparent bridge mode was apparently still doing /something/. Reconfiguring the ONT by explicitly turning off the firewall, UPNP, etc, and setting up my unifi hardware to do the VLAN tagging instead of the ONT has 100% completely resolved my issues. I basically never see >4ms out of dpinger or ping with any settings now!

Thanks for the pointers. What a weekend.
